@baseUrl = http://localhost:3000/api
@contentType = application/json

# --------------------------------------------------------
# VARIABLES (From your Seed Script)
# --------------------------------------------------------
@userId = 230fc6dc-4203-43dc-afed-0914a3466742
@accountId = cb7f72ca-90e2-44f3-a886-db1712bf90e7
@categoryId = 7dea049a-aeea-4b1c-9078-b539624ce407
@currencyId = e52d3c3d-43c4-4399-80b5-434a2ee66d84

# --------------------------------------------------------
# FEATURE: Manage Transactions
# --------------------------------------------------------

### Create a New Income
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}

{
  "name": "REST Client Test",
  "amount": 1000,
  "type": "INCOME",
  "date": "2025-12-05T12:00:00.000Z",
  "accountId": "{{accountId}}",
  "categoryId": "{{categoryId}}",
  "currencyId": "{{currencyId}}"
}

### Create a New Expense
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}

{
  "name": "REST Client Test",
  "amount": 30.58,
  "type": "EXPENSE",
  "date": "2025-12-05T12:00:00.000Z",
  "accountId": "{{accountId}}",
  "categoryId": "{{categoryId}}",
  "currencyId": "{{currencyId}}"
}

### (Future) Get All Transactions
# GET {{baseUrl}}/transactions

### TEST: Insufficient Funds
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}

{
  "name": "Lamborghini",
  "amount": 1000000.00,
  "type": "EXPENSE",
  "date": "2025-12-05T12:00:00.000Z",
  "accountId": "{{accountId}}",
  "categoryId": "{{categoryId}}",
  "currencyId": "{{currencyId}}"
}

### Get Transactions for an Account
GET {{baseUrl}}/transactions?limit=3