@baseUrl = http://localhost:3000/api
@contentType = application/json

# --------------------------------------------------------
# VARIABLES (From your Seed Script)
# --------------------------------------------------------
@userId = 3db4100f-12a3-4514-933b-7a2d39931c20
@accountId = 27f8cbd3-220b-4821-9829-a627925ca110
@categoryId = 0d89a654-bc95-430e-90f4-87d09d337a34
@currencyId = f74ff912-39b5-4cb4-a64e-3a27437bb53f

# --------------------------------------------------------
# FEATURE: Manage Transactions
# --------------------------------------------------------

### Create a New Income
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}
x-user-id: {{userId}}

{
  "name": "Salary Deposit",
  "amount": 1000,
  "type": "INCOME",
  "date": "2025-12-05T12:00:00.000Z",
  "accountId": "{{accountId}}",
  "categoryId": "{{categoryId}}",
  "currencyId": "{{currencyId}}"
}

### Create a New Expense
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}
x-user-id: {{userId}}

{
  "name": "Grocery Run",
  "amount": 30.58,
  "type": "EXPENSE",
  "date": "2025-12-05T12:00:00.000Z",
  "accountId": "{{accountId}}",
  "categoryId": "{{categoryId}}",
  "currencyId": "{{currencyId}}"
}

### TEST: Insufficient Funds (Should fail with 400)
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}
x-user-id: {{userId}}

{
  "name": "Lamborghini",
  "amount": 1000000.00,
  "type": "EXPENSE",
  "date": "2025-12-05T12:00:00.000Z",
  "accountId": "{{accountId}}",
  "categoryId": "{{categoryId}}",
  "currencyId": "{{currencyId}}"
}

### Get All Transactions (With Filters)
GET {{baseUrl}}/transactions?limit=5
x-user-id: {{userId}}

### Get Transactions for a specific Account
GET {{baseUrl}}/transactions?accountId={{accountId}}
x-user-id: {{userId}}


# --------------------------------------------------------
# FEATURE: Manage Accounts
# --------------------------------------------------------

### Create an account
POST {{baseUrl}}/accounts
Content-Type: {{contentType}}
x-user-id: {{userId}}

{
  "name": "ING Netherlands",
  "isMain": true,
  "currencyId": "{{currencyId}}"
}

### Get accounts (Should calculate balance)
GET {{baseUrl}}/accounts
x-user-id: {{userId}}

# --------------------------------------------------------
# SECURITY TEST
# --------------------------------------------------------

### TEST: Unauthorized Access (Missing Header)
# Expected: 401 Unauthorized
GET {{baseUrl}}/accounts